//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class B301_BlogEntities : DbContext
    {
        public B301_BlogEntities()
            : base("name=B301_BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etiket> Etiket { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kulllanici> Kulllanici { get; set; }
        public virtual DbSet<Makale> Makale { get; set; }
        public virtual DbSet<MakaleType> MakaleType { get; set; }
        public virtual DbSet<Resim> Resim { get; set; }
        public virtual DbSet<SiteTakip> SiteTakip { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
        public virtual DbSet<ZiyaretciIPLog> ZiyaretciIPLog { get; set; }
    }
}
