//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makale()
        {
            this.Yorum = new HashSet<Yorum>();
            this.Etiket = new HashSet<Etiket>();
            this.Resim1 = new HashSet<Resim>();
        }
    
        public int id { get; set; }
        public string Baslik { get; set; }
        public string İcerik { get; set; }
        public System.DateTime YayimTarihi { get; set; }
        public int KategoriID { get; set; }
        public int MakaleTypeID { get; set; }
        public System.Guid YazarID { get; set; }
        public int KapakResimID { get; set; }
        public int Goruntulenme { get; set; }
        public int Begeni { get; set; }
        public bool Aktif { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Kulllanici Kulllanici { get; set; }
        public virtual MakaleType MakaleType { get; set; }
        public virtual Resim Resim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiket> Etiket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resim> Resim1 { get; set; }
    }
}
